apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:IR+K0KYEOY3Szl2k9MA5AdtzEAZJiDsZW9hqBq5kmM+bpW55dtl3baMCC3oeOwN42m/OmQNWd7oFMqGjnGGbGzJph+f26KULTE7wYj3+FhO9uYVb/66BQOp7BYcJDy5H9Wo3JfenC5Ws2Na6GgYtGAEYXeVWZenfFlpC8+j6034R+M60IjLSgisBY6p4VyjSXJUeJ0gNmXZ47sDFHRrTqP2IIUtA6zQaxCq/K7IUbva7bfEXuR3kNyWa1h63BTq4u1QPJ8qpWCbcNM0Rzj8sxTKgk+Mx+zMv4C9Pu6sDppEa6XHF,iv:aMFoz9cTruykMoiD1vpsklx8ei/Ev/UqU8UI4EV4t50=,tag:5XxlXnjRWO0Xnsuyz/hjjw==,type:str]
kind: Secret
metadata:
    name: ghcr-pull-secret
    namespace: cachelab-staging
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwd0FSRVNDWHVqSWNCUlF0
            ZDJ0OFZPTzlENE9XMGxRcmdYOWJwWWM2TUJFCnBYMW1wZEtTUDQ2TzFnNUxLTTZL
            MGQrZGJBSFRrM3ZwZzBJVncvYnNQUWMKLS0tIFV2V28xTUFoWnBscmp2RE1tYlZS
            ekpmaUxlbHlna2drRzVzQ1F5V09GOW8KkdLuHDYiaxNX8EgfhqjlWAWckY5m0SCk
            Zhy1HFrVdj75EBfUKGpsiY87u1gmPDYRR4x56gCNuZNvh+Ypt3gn0w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pr2ytwrcjmvydzhxazn4hhch328rag0dtzm789exd2qa440tyyvs4zupkl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-28T13:25:06Z"
    mac: ENC[AES256_GCM,data:707lANL8mLC3mbOoiBqwEREOtW0NWOZYmLn9K6HfRUn/lybrt1fsnRs89vqTqr8LeGpuuKuBb28XXPzhU4JMMn+5DhX5srSUA+KH0ehhHw89Ar1gNs5yn9srjkrfi1krceBWaN/UaYFWuzT0XEXDkhIYrxgq+y9Y4GwKSD+/JME=,iv:mdnt43b4EFDeuR0Aww3NnRaXWlqr7bsN2MgcaFLdhgE=,tag:y5qlbRMtulmHTeoGj6SYYQ==,type:str]
    version: 3.13.3
