---
- name: Define Umami funnels
  ansible.builtin.set_fact:
    umami_funnels:
      - name: Learning funnel
        description: Learn content to completed exercise
        parameters:
          window: 60
          steps:
            - type: event
              value: learn-open
              filters: []
            - type: event
              value: exercise-start
              filters: []
            - type: event
              value: exercise-complete
              filters: []

      - name: Exercise funnel
        description: Exercise start to first answer to completion
        parameters:
          window: 60
          steps:
            - type: event
              value: exercise-start
              filters: []
            - type: event
              value: exercise-answer
              filters: []
            - type: event
              value: exercise-complete
              filters: []

      - name: Challenge funnel
        description: Challenge start to completion
        parameters:
          window: 60
          steps:
            - type: event
              value: challenge-start
              filters: []
            - type: event
              value: challenge-complete
              filters: []

- name: Provision Umami funnels for configured websites
  ansible.builtin.include_tasks: umami-funnels-website.yml
  loop: "{{ umami_websites | dict2items }}"
  loop_control:
    loop_var: umami_website
    label: "{{ umami_website.key }}"
