all:
  vars:
    ansible_user: ubuntu

  children:
    app:
      hosts:
        platform-app-01:
          ansible_host: 135.125.75.237

    observability:
      hosts:
        platform-observability-01:
          ansible_host: 135.125.75.36