---
- name: Configure observability server
  hosts: observability
  become: true

  roles:
    - common
    - hardening
    - firewall
    - docker
    - node_exporter

- name: Deploy observability stack
  hosts: observability
  become: true

  roles:
    - observability