apiVersion: v1
kind: Secret
metadata:
    name: alloy-loki-credentials
    namespace: alloy
type: Opaque
stringData:
    LOKI_USERNAME: ENC[AES256_GCM,data:wSBx/oA=,iv:1bl7I+JHsD7jR//9i8qTzhlSqTK6Ou96YyVqzwrlBSI=,tag:Z0XHsMP7kQNZVmR1h+OpwA==,type:str]
    LOKI_PASSWORD: ENC[AES256_GCM,data:tI7MO/NtJTL61XMdX+KtSJThVPjzlFmCNq0DNveeFOfH8OF2s4MNZWxez/4=,iv:I0XS3AykyNRSVtfSEYE6h9Lf5KuIOykzD0jiTY41keI=,tag:7mLMH2PQU2iN0Tqv+4a83g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4ZU9Tc3JxdmNvbkpJTFc3
            aE12eDNSbHhYUmZJWVpNeHpEK0RKNnNNS1F3CmUxU1EyZFQ4ck12NmR6eEpnTWha
            d3NtZlVnRXVWZERsbm1XOFVLbW5YV1kKLS0tIExxa0RMQis4REM4ZUl2eUE2dzdK
            L0h3UWFOTnlSNzVYeFBOSTUwOGM0TWsKsf+BJ/IDhfoiTC23I7KxKRinh0/1gRtZ
            Ami3/JITM7q0NFYujRO64U3bDyGycl9pt1ZBUlpVqchzPEW/nOd5gA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pr2ytwrcjmvydzhxazn4hhch328rag0dtzm789exd2qa440tyyvs4zupkl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-29T13:35:05Z"
    mac: ENC[AES256_GCM,data:cSTH9gpFVAuzgO170dbUHVh7GA0TqYazfqlVPtfawdmX6WuYTDlJVg4EivKXPlhCm104Bn1qUzMoZT5POvrZrC8QnTX8LIMgV4l7wu9fYcebAsVoPPVbjrbhGpC0pv7uKBKtjm+PG46u4ncF/MQiyf6wZN2F8wVqzCkYyvZ6R9M=,iv:PSTZapz7Kp7eHcPxh6GgaUGdjN7HxoPa4eAeCIZN8sU=,tag:a6m4/HM+wibsVeyMtXu0pg==,type:str]
    version: 3.13.3
