apiVersion: v1
kind: ConfigMap
metadata:
  name: ksops-plugin
  namespace: argocd
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: ksops
    spec:
      version: v1

      discover:
        fileName: "secret-generator.yaml"

      generate:
        command:
          - kustomize
        args:
          - build
          - --enable-alpha-plugins
          - --enable-exec
          - .