apiVersion: apps/v1
kind: Deployment
metadata:
  name: cachelab
spec:
  replicas: 1

  selector:
    matchLabels:
      app.kubernetes.io/name: cachelab

  template:
    metadata:
      labels:
        app.kubernetes.io/name: cachelab

    spec:
      imagePullSecrets:
        - name: ghcr-pull-secret

      containers:
        - name: frontend
          image: ghcr.io/glefer/cachelab-frontend@sha256:981d4c77646d3b0afcd113d632f442a84e28038680788812197f45e2d31c1658

          ports:
            - name: http
              containerPort: 8080

          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 2
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10

          resources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              cpu: 200m
              memory: 128Mi