apiVersion: v1
data:
    users: ENC[AES256_GCM,data:k9Bh8yr+yQlvx5OXLJ2ijYgKqYbUoAAYkAzfms5sNlJe6aFlMoauHRSsftBzDlPPlhuPdNR5u34El+GB/mNkdJyaGM66NL/TH58SWoBP9L1iIAF6Ji8suk3OqJ8=,iv:/WLTvHATrtB/UnYc7mlyNrZ/k9pWe8D+8RYD9h3MCh4=,tag:N2eEJsj0oMvvDhnwvpeGHg==,type:str]
kind: Secret
metadata:
    name: staging-basic-auth
    namespace: cachelab-staging
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKSnBMMzM0dUlMelVtV2lk
            NmVXSVBveXY4ZW9XcVQzRDV1RFJZblAxelRJCkJGR09KaytiNFlJZEE4WUx4SXEr
            LzFmU1JmZmxvcDVGY2sydklZVDZ2dTgKLS0tIFMyOTdCMmx2T1RMUlk3RzRzb1ls
            OElFZjJlZmRNQnozVEZnZ3ZrZ3psaDQKVTgRziNVDuBZbQaWj4nVOqde6fAQ+RKF
            g0vWGATOchyjd4OztXuFQBEXcKwRu2Q7JNbMQ2l/t+SrTdNv1z2NUA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pr2ytwrcjmvydzhxazn4hhch328rag0dtzm789exd2qa440tyyvs4zupkl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-28T13:29:03Z"
    mac: ENC[AES256_GCM,data:/wyI/nhHrrZv2zGPiZ4H0ZJsVVHhkZJbE/MXnpK/MGi/kYQC2IrtjsDCUcl7a6wGgs0OLI+2+zkdK2uipE1pntZbWpsj2Myy3qWyvtARoxqaYvkYL9LnE6/glsnovWiPCDLM3o6345Z9nFsZzYhUX1Y7JV/bBEkSAuViiV0xH+U=,iv:Tnh+QjEcJRiJe+z3Lr4Sf9998Ui1y3TWM0li6hHrc0s=,tag:uAj0AolH4zeygHqsVxznJQ==,type:str]
    version: 3.13.3
