apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cachelab-staging

resources:
  - ../../base
  - ingress.yaml
  - middleware-auth.yaml
  - middleware-noindex.yaml
  - middleware-security.yaml

generators:
  - secret-generator.yaml