apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cachelab-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/glefer/gitops-infra.git
    targetRevision: main
    path: gitops/apps/cachelab/overlays/prod
    plugin:
      name: ksops-v1
  destination:
    server: https://kubernetes.default.svc
    namespace: cachelab-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: restricted
        pod-security.kubernetes.io/enforce-version: v1.37
        pod-security.kubernetes.io/audit: restricted
        pod-security.kubernetes.io/audit-version: latest
        pod-security.kubernetes.io/warn: restricted
        pod-security.kubernetes.io/warn-version: latest
    syncOptions:
      - CreateNamespace=true
