apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-state-metrics
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-state-metrics
    targetRevision: 8.4.1
    helm:
      values: |
        prometheusScrape: true
        metricLabelsAllowlist:
          - pods=[app.kubernetes.io/name,app.kubernetes.io/component,app.kubernetes.io/part-of,observability.cachelab.fr/environment]
          - deployments=[app.kubernetes.io/name,app.kubernetes.io/component,app.kubernetes.io/part-of]

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true