apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - traefik.yaml
  - traefik-config.yaml
  - cert-manager.yaml
  - cert-manager-config.yaml
  - cachelab-staging.yaml
  - cachelab-prod.yaml
  - kube-state-metrics.yaml
  - kube-state-metrics-config.yaml
  - alloy.yaml