apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://traefik.github.io/charts
    chart: traefik
    targetRevision: 37.1.1

    helm:
      values: |
        deployment:
          replicas: 1

        service:
          type: LoadBalancer

        ports:
          web:
            expose:
              default: true
          websecure:
            expose:
              default: true

  destination:
    server: https://kubernetes.default.svc
    namespace: traefik

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true