apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://traefik.github.io/charts
    chart: traefik
    targetRevision: 41.6.0
    helm:
      values: |
        deployment:
          replicas: 1

        service:
          type: LoadBalancer

        ports:
          web:
            expose:
              default: true

          websecure:
            expose:
              default: true

        additionalArguments:
          - --entryPoints.web.http.redirections.entryPoint.to=:443
          - --entryPoints.web.http.redirections.entryPoint.scheme=https
          - --entryPoints.web.http.redirections.entryPoint.permanent=true
          - --accesslog=true

  destination:
    server: https://kubernetes.default.svc
    namespace: traefik

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true