apiVersion: v1
kind: Secret
metadata:
    name: kube-state-metrics-basic-auth
    namespace: kube-system
type: Opaque
stringData:
    users: ENC[AES256_GCM,data:cbWdmmRHqmnH9F4OnE9tr43ARVSqjJBVGs8U3EYQllTzpLU9JnOIBXwKKNHCbq/gdQju7vswZJ80YjFKMwZKAVu/ND9VrHs=,iv:fkoQPuvQxtpd2qTGFxjjM5Xwv/oGQqI9gb0NLD0oHrY=,tag:fKyUFppdIuFtccr9z2dlJQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQaWloV3pubEtZTCtVMWFo
            VFFKOU9iRXZnWDVLSWZ5eWw2RVFPUjJvdlEwCmk1ZDRXcFJ1NHVzNHRhYlZ0dkhw
            bkpuL0t6M1pORHdHOTd2Qkg1QzRSVHcKLS0tIHdzS0k3VHphalVkN216WUZRWXFI
            NEZiR29jU3VDL2ZiQXkwZzJlRVNBL2cK6+/+Y1kWlDa0WxBFZ8/bJAL6xsh6AH7f
            y+QhfJmtn9Bu2wFU/tFljMOF3WMRM9v7QWnP3cy50E43XsvVx3SrFw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pr2ytwrcjmvydzhxazn4hhch328rag0dtzm789exd2qa440tyyvs4zupkl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-29T12:28:55Z"
    mac: ENC[AES256_GCM,data:ksabzO1XxCsMLrx+1ep06Mfjv/wM1cp/QJTEJdgGi0dThyTc0nBa8PjuQYIMhyo1g2pmwDEDwMJkl57YEKTcTdwmi27LNg/I53Mcef/Gz6U30T218n2HWliHbx25JSMPW9PlwweNkZUr3Jcw8gLRMdvH8WZyHT8nAcxXUtWeaIE=,iv:Zehdk3xdhvFYv/WaBnWjRja0Cbh1lZCBfSGy3XvljEo=,tag:c9bAeP50S7x1oxQ4ZWuLsg==,type:str]
    version: 3.13.3
