apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: kube-state-metrics-secrets
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - basic-auth-secret.enc.yaml